### ISSUE TITLE
Some lines are not perpendicular

### ISSUE THREAD

**Issue by salahelfarissi** [salahelfarissi/interactive-iav-campus-map#6]
- The buildings (Direction de formation en agronomie) weren't drew as rectangles and are slightly inclined.
<img src="https://user-images.githubusercontent.com/23387408/155836302-5e305fd2-688e-41dd-a8ef-3629f2bcba7a.png" alt="building" width="200"/>

- Also, please execute the following code in sequence to add my changes to your repo :
`git remote add upstream https://github.com/salahelfarissi/interactive-iav-campus-map.git`
`git fetch upstream`
`git rebase upstream/master` 

- Here is a link where you can find some useful photos: [IAV Photos](https://www.flickr.com/photos/161618249@N03/albums/)

Regards @abdellatifabdane

**Comment by abdellatifabdane** [comment]
Le problème c'est que y'en a des bâtiments qui n'ont pas une forme
rectangulaire, et les formes que présentent qgis sont des formes simples
(rectangle, cercle, ellipse).
Personnellement je propose de les digitaliser en utilisant une forme
rectangulaire même si cela est contradictoire avec la réalité.
Sinon qu'est ce que vous proposez comme solution ?

Cordialement

**Comment by salahelfarissi** [comment]
For an intermediate segment, you can add an arc instead of segment. QGIS has this ability as far as I am concerned.

**Comment by salahelfarissi** [comment]
Send me a meeting to elfarissisalaheddine@iav.ac.ma if you need to discuss the issue.
